# Docker containers used to test this crate.
version: "3"
services:
  selenium:
    image: selenium/standalone-chrome:latest
    volumes:
      - "/dev/shm:/dev/shm"
    ports:
      - "4444:4444"
    environment:
      - NODE_MAX_INSTANCES=4
      - NODE_MAX_SESSION=4
  webappdemo:
    image: stevepryde/thirtyfour_testapp:0.1.0
    ports:
      - "8000:80"
